name: data
on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch: {}
  push:
    paths:
      - .github/workflows/flat.yml
jobs:
  scheduled:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repo
        uses: actions/checkout@v3
      - name: Create data directory
        run: mkdir -p data
      - name: Fetch country names
        uses: githubocto/flat@v3
        with:
          http_url: https://www.canada.ca/content/dam/ircc/documents/json/data-country-name-en.json
          downloaded_filename: data/data-country-name-en.json
      - name: Fetch processing times
        uses: githubocto/flat@v3
        with:
          http_url: https://www.canada.ca/content/dam/ircc/documents/json/data-ptime-en.json
          downloaded_filename: data/data-ptime-en.json
      - name: Fetch data for in Canada services
        uses: githubocto/flat@v3
        with:
          http_url: https://www.canada.ca/content/dam/ircc/documents/json/data-ptime-non-country-en.json
          downloaded_filename: data/data-ptime-non-country-en.json
