name: Weekly IRCC Snapshot
on:
  schedule:
    - cron: '0 12 * * 3'  # Every Wednesday 6:00 AM CST / 7:00 AM CDT
  workflow_dispatch: {}   # Allow manual run

jobs:
  weekly_snapshot:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repo
        uses: actions/checkout@v3

      - name: Create data directory
        run: mkdir -p data

      # Fetch the IRCC JSON files
      - name: Fetch country names
        uses: githubocto/flat@v3
        with:
          http_url: https://www.canada.ca/content/dam/ircc/documents/json/data-country-name-en.json
          downloaded_filename: data/data-country-name-en.json

      - name: Fetch processing times
        uses: githubocto/flat@v3
        with:
          http_url: https://www.canada.ca/content/dam/ircc/documents/json/data-ptime-en.json
          downloaded_filename: data/data-ptime-en.json

      - name: Fetch in-Canada services
        uses: githubocto/flat@v3
        with:
          http_url: https://www.canada.ca/content/dam/ircc/documents/json/data-ptime-non-country-en.json
          downloaded_filename: data/data-ptime-non-country-en.json

      # Save a weekly snapshot
      - name: Save weekly snapshot
        run: |
          YEAR=$(date +'%Y')
          WEEK=$(date +'%V')
          SNAPSHOT_DIR="weekly"
          mkdir -p $SNAPSHOT_DIR
          
          # Save all three files with descriptive names
          cp data/data-country-name-en.json "$SNAPSHOT_DIR/$YEAR-W$WEEK-country-names.json"
          cp data/data-ptime-en.json "$SNAPSHOT_DIR/$YEAR-W$WEEK-processing-times.json"
          cp data/data-ptime-non-country-en.json "$SNAPSHOT_DIR/$YEAR-W$WEEK-in-canada-services.json"
          
          # Keep only newest 52 weeks for each file type
          for suffix in "country-names" "processing-times" "in-canada-services"; do
            ls -1 $SNAPSHOT_DIR/*-$suffix.json 2>/dev/null \
              | sort -r \
              | tail -n +53 \
              | xargs -r rm -f
          done

      # Create weekly index file (newest first)
      - name: Create weekly index file
        run: |
          SNAPSHOT_DIR="weekly"
          if [ -d "$SNAPSHOT_DIR" ] && [ "$(ls -A $SNAPSHOT_DIR/*.json 2>/dev/null)" ]; then
            ls -1 $SNAPSHOT_DIR/*.json \
              | grep -v 'index.json' \
              | sed 's|.*/||' \
              | sort -r \
              | jq -R -s -c 'split("\n")[:-1]' > $SNAPSHOT_DIR/index.json
            git add $SNAPSHOT_DIR/index.json
            echo "Created index with $(cat $SNAPSHOT_DIR/index.json | jq length) files"
          else
            echo "No weekly snapshots found, skipping index creation"
          fi

      # Commit and push changes
      - name: Commit and push
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          
          # Check if there are any changes to commit
          if [ -n "$(git status --porcelain)" ]; then
            git add weekly/
            git commit -m "Weekly snapshot for $(date +'%Y-%m-%d')"
            git push
            echo "Changes committed and pushed successfully"
          else
            echo "No changes to commit"
          fi
